config/routes.rb
InboxesApp::Application.routes.draw do
  get "posts/index"

  get "posts/show"

  get "posts/new"

  get "posts/create"

  get "posts/view"



  devise_for :users

  root :to => "home#index"

  mount Inboxes::Engine => "/inboxes"




  resources :discussions, :except => :edit, :module => :inboxes do
    resources :messages, :only => [:create, :index]
    resources :speakers, :only => [:create, :destroy]
    member do
      post 'leave'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:index, :create], Discussion
can :read, Discussion do |discussion|
  discussion.can_participate?(user)
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :from, :till, :vacation, :vacation_type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
  validates :name, :presence => true, :uniqueness => true
  
  # SHOULD ADD this while installation
  has_many :discussions
  
  has_inboxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
   before_filter :assign_unread_discussions
  
  private
  
  def assign_unread_discussions
    @unread_discussions_count = Discussion.unread_for(current_user).count if user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/inboxes/base_controller.rb
class Inboxes::BaseController < ApplicationController
  private

  def init_discussion
    @discussion = Discussion.find(params[:discussion_id])
  end
end

app/controllers/inboxes/discussions_controller.rb
class Inboxes::DiscussionsController < ApplicationController
	 load_and_authorize_resource
  before_filter :load_and_check_discussion_recipient, :only => [:create, :new]

  def index
    @discussions = current_user.discussions
  end

  def show
    @discussion.mark_as_read_for(current_user)
  end

  def new
    @discussion.messages.build
  end

  def destroy
    @discussion.destroy

    flash[:notice] = t("discussions.removed")
    begin
      redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to discussions_url
    end
  end

  def create
    @discussion.add_recipient_token current_user.id

    @discussion.messages.each do |m|
      m.discussion = @discussion
      m.user = current_user
    end

    if @discussion.save
      redirect_to discussion_url(@discussion), :notice => t("discussions.started")
    else
      render :action => "new"
    end
  end

  private

  def load_and_check_discussion_recipient
    # initializing model for new and create actions
    @discussion = Discussion.new(params[:discussion].presence || {})

    # checking if discussion with this user already exists
    if @discussion.recipient_ids && @discussion.recipient_ids.size == 1
      user = User.find(@discussion.recipient_ids.first)
      discussion = Discussion.find_between_users(current_user, user)
      if discussion
        # it exists, let's add message and redirect current user
        @discussion.messages.each do |message|
          Message.create(:discussion => discussion, :user => current_user, :body => message.body) if message.body
        end
        # redirecting to that existing object
        redirect_to discussion_url(discussion), :notice => t("discussions.already_exists", :user => user[Inboxes::config.user_name])
      end
    end
  end
end

app/controllers/inboxes/messages_controller.rb
class Inboxes::MessagesController < Inboxes::BaseController
  load_and_authorize_resource :discussion
  load_resource :message, :through => :discussion, :shallow => true

  def create
    @message.user = current_user
    @message.discussion = @discussion
    @message.save

    respond_to do |format|
      format.html { redirect_to discussion_url(@message.discussion) }
      format.js
    end
  end
end

app/controllers/inboxes/speakers_controller.rb
class Inboxes::SpeakersController < Inboxes::BaseController
  load_and_authorize_resource :discussion
  load_resource :speaker, :through => :discussion, :shallow => true

  def create
    raise ActiveRecord::RecordNotFound unless params[:speaker] && params[:speaker][:user_id]
    @user = User.find(params[:speaker][:user_id])
    flash[:notice] = t("speakers.added") if @discussion.add_speaker(@user)
    redirect_to discussion_url(@discussion)
  end

  def destroy
    @speaker = Speaker.find(params[:id])
    @speaker.destroy
    flash[:notice] = @speaker.user == current_user ? t("discussions.leaved") : t("speakers.removed")
    redirect_to @discussion.speakers.any? && @discussion.can_participate?(current_user) ? discussion_url(@discussion) : discussions_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

 def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      redirect_to root_url
  end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<!-- <h3>Home</h3>
<% if user_signed_in? %>
  <%= link_to "Log uit", destroy_user_session_path, :method => :delete %>
  <%= link_to "Inbox", discussions_path %>
<% else %>
  
  <%= link_to "Registreren", new_user_registration_path %>
  <% end %> -->




<div class="logo">
<%= image_tag ("logo.png") %>
</div>
<div class="row clearfix">
<div class="col-md-12 column">
<div class="row clearfix">
<div class="col-md-12 column"> 
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="navbar-header">
<a class="navbar-brand" href="#">Reismetmij.nl</a>
</div>	
<ul class="nav nav-pills navbar-right">
<li>
<%= link_to "Inloggen", user_session_path %>
</li>
</ul>
</nav>
</div>
</div>
<div class="row clearfix">
<div class="col-md-12 column slogan">
<h1>Je hoeft niet alleen<br/> te reizen, 
<span class="bold">Reismetmij.</span></h1>
<h2> Vind hier je ideale reispartner.</h2>
<span><button class="btn btn-primary btn-lg oproep" data-toggle="modal" data-target=".bs-example-modal-lg">Plaats een oproep</button></span>

<br/>
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
<div class="modal-dialog modal-lg">
<div class="modal-content">




</div>
</div>
</div>

<span  class="of bold">of</span>
<div class="waar_heen">
<div class="col-lg-6">
<div class="input-group">
<input type="text" class="form-control" placeholder="Waar wil je heen?">
<span class="input-group-btn">
<button class="btn btn-default" type="button">Zoek</button>
</span>
</div>
</div>
</div>
</div>
</div>
<div class="row clearfix">
<div class="col-md-12 column">
</div>
</div>
</div>

app/views/inboxes/discussions/_form.html.erb
<%= form_for @discussion, :url => discussions_path do |f| %>
    <%= f.label :recipient_tokens %>
    <%=  select_tag "discussion[recipient_tokens]", options_from_collection_for_select(User.all, :id, Inboxes::config.user_name), :multiple => true, :size => "4" %>

    <%=  f.fields_for :messages do |j| %>
      <%=  j.label :body %>
   
      <%=  j.text_area :body %>

<%= f.submit %>
    <% end %>

<% end %>

app/views/inboxes/discussions/index.html.erb
<h3>Inbox</h3>

<ul>
<%= @discussions.each do |discussion| %>

  <li>
    <%= link_to discussion.users.collect{|u| u[Inboxes::config.user_name]}.join(' | '), discussion_path(discussion) %><%= discussion.updated_at %>
  </li>

<% if %>
<% discussion.unread_for?(current_user) %>
<li> <%= pluralize(discussion.unread_messages_count_for(current_user), "reactie") %></li>
<% else %>
<li>    <p>Geen ongelezen berichten</p> </li>



</ul>
<% end %>
<% end %>

<%= link_to "nieuw bericht maken", new_discussion_path %>

app/views/inboxes/discussions/new.html.erb
<h1>Reageer</h1>

<%= render "form" %>

<%= link_to "All discussions", discussions_path %>

app/views/inboxes/discussions/show.html.erb
  <h1>Reizigers</h1>
<% @discussion.speakers.each do |speaker| %>
  
    <%= speaker.user[Inboxes::config.user_name] %>
    <%= link_to '(verwijderen)', discussion_speaker_path(@discussion, speaker), :method => :delete %>
   
 <% if user_signed_in? %>
        Unread messages: <%= @unread_discussions_count %>
    
<% available_users = User.all.map { |u| u unless @discussion.users.include?(u) }.delete_if { |w| w.nil? } %>

<% if available_users.any? do  %> 
<%= form_for Speaker.new, :url => discussion_speakers_path(@discussion) do |f| %>
    <%= f.label :user_id, "Reiziger toevoegen aan het" %>
    <%= f.collection_select :user_id, available_users, :id, :name %>
    <%= f.submit "Toevoegen" %>

<h3>berichten</h3>

<% end %>
  <%= render @discussion.messages, :as => :message %>

<h3>Bericht schrijven</h3>
<%= render "inboxes/messages/form" %> 


  <%=  link_to "Gesprek verwijderen", discussion_speaker_path(@discussion, @discussion.find_speaker_by_user(current_user)), :method => :delete unless @discussion.private? %>
  <%=  link_to "Inbox", discussions_path %>

  
    
      <% end %>
         <% end %>
          <% end %>
          <% end %>

app/views/inboxes/messages/_form.html.erb
<%= form_for Message.new, :url => discussion_messages_path(@discussion.id), :method => :post, :remote => true do |f| %>
    
  
     
      <%= f.text_area :body %><br>
    <%= f.submit "Plaatsen" %>

    <% end %>

app/views/inboxes/messages/_message.html.erb
<%= message.user[Inboxes::config.user_name] %>
     @ 
      <%= l(message.created_at) %> <br>
   
    <%= message.body %>

app/views/inboxes/messages/create.js.erb
<% inboxes_faye_broadcast "/discussions/#{@message.discussion.id}" do %> 
  $("#messages_box").append("<%= escape_javascript render(@message) %>");
  $("#new_message")[0].reset();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  <title>Reis met mij</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,700,600,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

<%= csrf_meta_tag %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<%= yield(:head) %>
</head>


<body>
  <div class="container">
  <%= render "partials/header" %>

  <%= yield %>
</div>
</body>

</html>

app/views/posts/create.html.erb
%h1 Posts#create
%p Find me in app/views/posts/create.html.haml

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
     
      <%= f.label :vacation %>
      <%= f.text_field :vacation %>



      <%= f.submit "Maak account", class: "btn btn-md btn-default" %>

    <% end %>

app/views/posts/show.html.erb
%h1 Posts#show
%p Find me in app/views/posts/show.html.haml